# Generated by Django 3.1.3 on 2021-04-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='zt_Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='注册邮箱')),
                ('phone_number', models.CharField(max_length=14, unique=True, verbose_name='电话号码')),
                ('zt_register_status', models.IntegerField(choices=[(2, '未知'), (1, '失败'), (0, '成功')], verbose_name='注册状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
